FROM python:3.8-buster

WORKDIR /app

COPY ./requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY ./job ./job
COPY ./db ./db
COPY ./main_job.py ./main_job.py

CMD [ "python3", "main_job.py" ]