apiVersion: batch/v1
kind: CronJob
metadata:
  name: job
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: job
        spec:
          restartPolicy: Never
          concurrencyPolicy: Forbid
          containers:
            - name: python
              image: "{{ .Values.werf.image.job }}"
              workingDir: /app
              env:
                - name: POSTGRES_URI
                  value: "{{ .Values.postgres.uri }}"
                - name: ETHERSCAN_API_KEY
                  value: "{{ .Values.etherscan.apiKey }}"
                - name: ETHERSCAN_BASE_URL
                  value: "{{ .Values.etherscan.baseUrl }}"
                - name: WEB3_PROVIDER_URL
                  value: "{{ .Values.web3.providerUrl }}"
                - name: REDIS_URI
                  value: "redis://{{ .Release.Name }}-redis-master"
                - name: PROXY_HOST
                  value: "{{ .Values.proxy.host }}"
                - name: PROXY_PORT
                  value: "{{ .Values.proxy.port }}"
